<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.1, minimum-scale=1.0, user-scalable=no" />
    <title>!{title}</title>
    <meta property="og:title" content="!{title}">
    <meta property="og:url" content="!{url}">
    <meta property="og:site_name" content="!{site_name}">
    <meta property="og:type" content="!{type}">
    <meta property="og:image" content="!{image}">
    <meta property="og:description" content="!{description}">
    <meta property="article:published_time" content="!{published_time}">
    <meta name="description" content="!{description}">
    <meta property="article:modified_time" content="!{modified_time}">
    <meta name="keywords" content="!{keywords}">
    <meta name="author" content="!{author}">

    <link rel="shortcut icon" href="!{favicon}">
    <link rel="icon" type="image/png" href="!{favicon}" sizes="192x192">
    <link rel="apple-touch-icon" sizes="180x180" href="!{favicon}">

    <link href="/fonts/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <script src="/js/jquery-2.1.4.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/newcss.css">
    <script src="/js/javascript.js"></script>
    <base href="/">
</head>